### ISSUE TITLE
[Question]: How to access array item in response body?

### ISSUE THREAD

**Issue by DenisSperansky** [crossplane-contrib/provider-http#100]
Hi!
I get an array of objects as response with my `Disposablerequest`. 
```
[
  {
    "created_at": "2022-05-02T14:16:39.127Z",
    "dataSourceNames": [],
    "description": "description",
    "id": "9999",
    "idLegalEntities": [],
    "idSourceNames": [],
    "name": "Foo",
    "updated_at": "2022-06-05T16:28:26.313Z"
  },
...
]
```
 First I've tried to use JQ filter to find required id like this:
```
apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: obtain-scope-id
spec:
  deletionPolicy: Orphan
  forProvider:
    url: https://.../api/v1/scopes
    method: GET
    headers:
      Content-Type:
        - "application/json"
    secretInjectionConfigs:
      - secretRef:
          name: "name"
          namespace: "namespace"
        keyMappings:
          - secretKey: scopeId
            responseJQ: ".body[]|select(.name==\"Foo\")|.id"
  providerConfigRef:
    name: http-session-token-auth
``` 
which doesn't work.
Then I've decided to check if I can use something much simplier:
```
...
            responseJQ: ".body[0]"
...
```
I get `scopeId: '['` injected in the secret. Is body is treated as a string for some reason? Is it intended behaviour or I'm using it incorrerctly?
