### ISSUE TITLE
Specifying content type in request to application/x-www-form-urlencoded fails

### ISSUE THREAD

**Issue by mustafaStakater** [crossplane-contrib/provider-http#18]
### What happened?
Specifying content type in request to application/x-www-form-urlencoded and setting the body to **param1=val1&param2=val2** gives
```
Warning  CannotCreateExternalResource  4m7s (x28 over 24m)  managed/request.http.crossplane.io  something went wrong: unexpected token "&"
```

### How can we reproduce it?

Deploying a request resource with following spec
```
apiVersion: http.crossplane.io/v1alpha1
kind: Request
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    mappings:
      - headers:
          Content-Type:
            - application/x-www-form-urlencoded
        method: POST
        url: >-
          (.payload.baseUrl + "/" +
          "some/path/")
    payload:
      baseUrl: 'https://some-url'
      body: param1=val1&param2=val2
  managementPolicy: FullControl
  providerConfigRef:
    name: http-conf

```

### What environment did it happen in?
Crossplane version: 1.14.0
Distribution: Openshift

**Comment by arielsepton** [comment]
Thanks for flagging this! After checking out the issue, it seems like the problem lies in how the body is set up in the request mappings.

In the provided Request resource, the body field within the mappings expects a jq filter. To fix this, just make sure to put the string in parentheses, like this:

```yaml
apiVersion: http.crossplane.io/v1alpha1
kind: Request
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    mappings:
      - headers:
          Content-Type:
            - application/x-www-form-urlencoded
        method: POST
        body: ("param1=val1&param2=val2")  # Enclose the string within parentheses
        url: >-
          (.payload.baseUrl + "/" +
          "some/path/")
    payload:
      baseUrl: 'https://some-url'
  managementPolicy: FullControl
  providerConfigRef:
    name: http-conf

```
That should sort out the unexpected token issue.

Oh, and I noticed you didn't include a GET mapping. Without it, the provider might struggle to validate that the resource is up to date. If you're looking to perform a one-time request, consider using the DisposableRequest resource instead. Here's a quick example:

```yaml
apiVersion: http.crossplane.io/v1alpha1
kind: DesposibleRequest
metadata:
  name: example
spec:
  deletionPolicy: Orphan
  forProvider:
    url:  https://some-url/some/path
    method: POST
    body: param1=val1&param2=val2
    headers:
      Content-Type:
        - application/x-www-form-urlencoded
  providerConfigRef:
    name: http-conf

```

No need to worry about jq here; just specify the body without parentheses and you're good to go!

Hope this helps! Let me know if you have any further questions or concerns.

**Comment by mustafa-be** [comment]
Hello, thanks ill check it out, i m working on doing a missing configuration in keycloak (feat missing in upstream tf provider), my workflow is 
- Generate a access token from keycloak api
- Use access token to perform the missing configuration against keycloak

> Oh, and I noticed you didn't include a GET mapping. Without it, the provider might struggle to validate that the resource is up to date.

If i understand it correctly, i would have to include get request as well making the overall flow to be 
- Generate a access token from keycloak api 
- Get configuration from keycloak
- Use access token to perform the missing configuration against keycloak

**Comment by arielsepton** [comment]
Thanks for sharing your workflow! It sounds like you’re on the right track. Considering your scenario, it seems you’ll need to perform three requests:

	1.	Use a DisposableRequest to retrieve the access token from the Keycloak API.
	2.	Use another DisposableRequest to retrieve the configuration data from Keycloak.
	3.	For your final action, whether it’s creating, updating, or deleting resources, you can choose between a DisposableRequest and a Request:
	•	If you’re performing a one-time action without managing any resources, like sending a single request to Keycloak, use a DisposableRequest.
	•	If you’re managing resources and need to ensure their state, such as creating or updating resources based on the retrieved configuration data, use a Request.

Just to clarify, DisposableRequest is typically used for one-time interactions, while Request is more suitable for managing resources through HTTP requests.

Let me know if you have any questions or need further clarification on implementing these steps.

**Comment by mustafa-be** [comment]
ok, thanks for the comprehensive reply, it helps. Ill go with a combination of desposible request + request for performing this configuration.

**Comment by mustafa-be** [comment]
I have a request that im making from cli against keycloak api using 
```
curl -d 'client_id=admin-cli&username=admin&password=a1b2c3&grant_type=password' https://keycloak-instance/realms/master/protocol/openid-connect/token
```
creating this resource as replacement for above command but it **fails** 
```
apiVersion: http.crossplane.io/v1alpha1
kind: DesposibleRequest
metadata:
  name: example-disposable-request
spec:
  deletionPolicy: Orphan
  forProvider:
    waitTimeout: 5m
    rollbackRetriesLimit: 5
    url:  https://keycloak-instance/realms/master/protocol/openid-connect/token
    method: POST
    body: |
            grant_type=password&client_id=admin-cli&password=a1b2c3&username=admin
    headers:
      Content-Type:
        - application/x-www-form-urlencoded
      Accept:
        - application/json
  providerConfigRef:
    name: http-conf

```

it might be something with the api but your insight would be helpful if any.
