### ISSUE TITLE
Nested JSON in PUT body

### ISSUE THREAD

**Issue by eldr0n** [crossplane-contrib/provider-http#27]
### What happened?
If the body of the put request contains a nested json, the provider-http fires another put request, even if the response of the get request contains said nested json.

I looked in to the code and it looks like nested jsons should be supported but i can't figure out where the problem is.

### How can we reproduce it?
```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: ceph-bucket-{{ .observed.composite.resource.spec.psn }}
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: ceph-bucket-{{ .observed.composite.resource.spec.psn }}
spec:
  forProvider:
    headers:
      Content-Type:
        - application/json
      Accept:
        - application/json
    payload:
      baseUrl: http://rgwapi-service.crossplane-system.svc/bucket
      body: |
        {
          "bucket": {{ .observed.composite.resource.spec.bucket | quote }},
          "owner": {{ .observed.composite.resource.spec.psn | quote }},
          "bucket_quota": {
            "enabled": {{ .observed.composite.resource.spec.quota.enabled }},
            "max_size_kb": {{ .observed.composite.resource.spec.quota.max_size_kb }}
          }
        }
    insecureSkipTLSVerify: true
    waitTimeout: 1m
    mappings:
      - method: POST
        url: .payload.baseUrl
        body: |
          {
            "bucket": .payload.body.bucket,
            "owner": .payload.body.owner,
            "bucket_quota": {
              "enabled": .payload.body.bucket_quota.enabled,
              "max_size_kb": .payload.body.bucket_quota.max_size_kb
            }
          }
      - method: GET
        url: (.payload.baseUrl + "/" + (.payload.body.bucket|tostring))
      - method: PUT
        url: (.payload.baseUrl + "/" + (.payload.body.bucket|tostring))
        body: |
          {
            "bucket": .payload.body.bucket,
            "owner": .payload.body.owner,
            "bucket_quota": {
              "enabled": .payload.body.bucket_quota.enabled,
              "max_size_kb": .payload.body.bucket_quota.max_size_kb
          }
      - method: DELETE
        url: (.payload.baseUrl + "/" + (.payload.body.bucket|tostring))
  providerConfigRef:
    name: http-conf
```

### What environment did it happen in?
Crossplane version: v1.16.0
provider-http version: v1.0.2

**Comment by arielsepton** [comment]
Hi there! @eldr0n 

I took a look at the issue, and it seems the body of the `PUT` mapping is not properly enclosed. 
>       - method: PUT
>         url: (.payload.baseUrl + "/" + (.payload.body.bucket|tostring))
>         body: |
>           {
>             "bucket": .payload.body.bucket,
>             "owner": .payload.body.owner,
>             "bucket_quota": {
>               "enabled": .payload.body.bucket_quota.enabled,
>               "max_size_kb": .payload.body.bucket_quota.max_size_kb
>           }

It should be:
```yaml 
- method: PUT
  url: (.payload.baseUrl + "/" + (.payload.body.bucket|tostring))
  body: |
    {
      "bucket": .payload.body.bucket,
      "owner": .payload.body.owner,
      "bucket_quota": {
        "enabled": .payload.body.bucket_quota.enabled,
        "max_size_kb": .payload.body.bucket_quota.max_size_kb
      }
    }
```
Let me know if this helps, so I can further investigate if needed.

**Comment by arielsepton** [comment]
I've tested a similar request and it worked as expected. Here's a working example:

```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: test
spec:
  forProvider:
    headers:
      Content-Type:
        - application/json
    payload:
      baseUrl: https://health-check.free.beeceptor.com/todos
      body: |
        {
          "bucket": "hi",
          "owner": "hi",
          "bucket_quota": {
            "enabled": "hi",
            "max_size_kb": "hi"
          }
        }
    mappings:
      - method: POST
        body: |
          {
            "bucket": .payload.body.bucket,
            "owner": .payload.body.owner,
            "bucket_quota": {
              "enabled": .payload.body.bucket_quota.enabled,
              "max_size_kb": .payload.body.bucket_quota.max_size_kb
            }
          }
        url: .payload.baseUrl
      - method: GET
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring)) 
      - method: PUT
        body: |
          {
            "bucket": .payload.body.bucket,
            "owner": .payload.body.owner,
            "bucket_quota": {
              "enabled": .payload.body.bucket_quota.enabled,
              "max_size_kb": .payload.body.bucket_quota.max_size_kb
            }
          }
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring)) 
      - method: DELETE
        url: (.payload.baseUrl + "/" + (.response.body.id|tostring))

  providerConfigRef:
    name: http-conf
```

Check the status to ensure the `GET` response contains the exact body as the `PUT` request. Here's the status for the provided `Request`:

```yaml
Status:
  ...
  Response:
    Body:   {
            "bucket": "hi",
            "owner": "hi",
            "bucket_quota": {
              "enabled": "hi",
              "max_size_kb": "hi"
            }
          }
    Status Code:  200
```
You can use the [Beeceptor URL](https://app.beeceptor.com/console/health-check) for testing, as I've configured the endpoints for `GET` and `POST` to match your use case.

Let me know if this helps!
