### ISSUE TITLE
DeploymentRuntimeConfig

### ISSUE THREAD

**Issue by wmendes-ionos** [crossplane-contrib/provider-http#50]
### What problem are you facing?

The majority of providers can use a DeploymentRuntimeConfig in order to configure specifics to the package-runtime container.
I couldn't find a way to configure one for the provider-http. How can I change the package-runtime container? e.g(Add env vars, mount volumes etc.)

### How could Crossplane help solve your problem?

Allow DeploymentRuntimeConfig for provider-http.

**Comment by arielsepton** [comment]
Hi, @wmendes-ionos the `provider-http` supports configuring the package-runtime container using `DeploymentRuntimeConfig`. Have you tried the following?

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-http
spec:
  package: <the desired provider-http package>
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: provider-http-runtime-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-http-runtime-config
spec:
  deploymentTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - --debug
```
This configuration should enable debug logs, for instance.
