### ISSUE TITLE
Allow to use GET only ? 

### ISSUE THREAD

**Issue by DrummyFloyd** [crossplane-contrib/provider-http#51]
by design it seems , that we need, to have a `POST` method in mappings

but is it possible to have the possibility, to have only `GET`

for instance

```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: manage-user
spec:
  forProvider:
    headers:
      Content-Type:
        - application/json
    insecureSkipTLSVerify: true
    mappings:
      - method: "GET"
        url: .payload.baseUrl + "/?length=34&lower=1&upper=1&int=1&special=0"
    payload:
      baseUrl: https://www.psswrd.net/api/v1/password

```

**Comment by arielsepton** [comment]
Hi @DrummyFloyd 

The `Request` resource is stateful, because of this, it requires a `POST` method. For your use case, you might consider using `DisposableRequest`:

```yaml 
apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: get-resource
spec:
  deletionPolicy: Orphan
  forProvider:
    url:  https://www.psswrd.net/api/v1/password/?length=34&lower=1&upper=1&int=1&special=0
    method: GET
    headers:
      Content-Type:
        - application/json
    insecureSkipTLSVerify: true
```
