### ISSUE TITLE
DELETE retried multiple times

### ISSUE THREAD

**Issue by irizzant** [crossplane-contrib/provider-http#60]
### What happened?

I'm using provider-http version 1.0.3.
I have the following Request

```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: port-team
spec:
  forProvider:
    waitTimeout: "5m"
    headers:
      Content-Type:
        - application/json
      Authorization:
        - Bearer {{${id}-port-token:crossplane-system:token}}
    payload:
      baseUrl: https://api.getport.io/v1/teams
      body: |
        {
          "name": "cost-center-${id}",
          "users": [user.email for user in parameters.users],
          "description": "Cost Center ${id} team"
        }
    mappings:
      - method: POST
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: .payload.baseUrl
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{${id}-port-token:crossplane-system:token}}
      - method: GET
        url: (.payload.baseUrl + "/" + .response.body.team.name)
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{${id}-port-token:crossplane-system:token}}
      - method: PUT
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: (.payload.baseUrl + "/" + .response.body.team.name)
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{${id}-port-token:crossplane-system:token}}
      - method: DELETE
        url: (.payload.baseUrl + "/" + .response.body.team.name)
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{${id}-port-token:crossplane-system:token}}
```

When I delete the MR, the Team is actually deleted successfully once but then the DELETE is retried and it fails with 404, see events order:
```
Events:
  Type     Reason                        Age                    From                                Message
  ----     ------                        ----                   ----                                -------
  Warning  CannotCreateExternalResource  3m40s (x6 over 3m40s)  managed/request.http.crossplane.io  something went wrong: failed to get secret 123-port-token:crossplane-system: Secret "123-port-token" not found
  Normal   CreatedExternalResource       3m39s                  managed/request.http.crossplane.io  Successfully requested creation of external resource
  Normal   UpdatedExternalResource       97s (x3 over 3m38s)    managed/request.http.crossplane.io  Successfully requested update of external resource
  Normal   DeletedExternalResource       94s                    managed/request.http.crossplane.io  Successfully requested deletion of external resource
  Warning  CannotDeleteExternalResource  28s (x6 over 93s)      managed/request.http.crossplane.io  something went wrong: HTTP DELETE request failed with status code: 404
```

### What environment did it happen in?
Crossplane version: 1.17.0

**Comment by arielsepton** [comment]
Hi,
Thanks for the details. I tried to reproduce the issue with the latest provider version, but couldn’t replicate it. I recommend upgrading and testing again. If the issue persists, feel free to share more details, and I’ll take another look.

**Comment by irizzant** [comment]
Hi @arielsepton 
I've just retried with provider 1.0.5 and Crossplane 1.17.1, the issue persists.

Here you can find the manifests I've tried (replace elements within `<...>`):
```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: port-token-request
spec:
  deletionPolicy: Orphan
  forProvider:
    url: https://api.getport.io/v1/auth/access_token
    method: POST
    body: |
      {
        "clientId": "{{ port:crossplane-system:port_client_id }}",
        "clientSecret": "{{ port:crossplane-system:port_client_secret }}"
      }
    headers:
      Content-Type:
        - application/json
    shouldLoopInfinitely: true
    nextReconcile: 1h
    secretInjectionConfigs:
      - secretRef:
          name: port-token
          namespace: crossplane-system
        secretKey: token
        responsePath: .body.accessToken
        setOwnerReference: true
---
apiVersion: v1
kind: Secret
metadata:
  name: port
  namespace: crossplane-system
type: Opaque
stringData:
  port_client_id: <PORT_CLIENT_ID>
  port_client_secret: <PORT_CLIENT_SECRET>
---
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: port-team
spec:
  forProvider:
    waitTimeout: "5m"
    headers:
      Content-Type:
        - application/json
      Authorization:
        - Bearer {{port-token:crossplane-system:token}}
    payload:
      baseUrl: https://api.getport.io/v1/teams
      body: |
        {
          "name": "cost-center-test",
          "users": ["<EMAIL>"],
          "description": "Cost Center test team"
        }
    mappings:
      - action: CREATE
        method: POST
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: .payload.baseUrl
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: OBSERVE
        method: GET
        url: (.payload.baseUrl + "/" + .response.body.team.name)
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: UPDATE
        method: PUT
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: (.payload.baseUrl + "/" + .response.body.team.name)
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: REMOVE
        method: DELETE
        url: (.payload.baseUrl + "/" + .response.body.team.name)
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
```

**Comment by arielsepton** [comment]
Hi, I looked into this and found the issue.  
All jq expressions used in the `Request` resource need to return `null` when a field is missing. Instead, `gojq` is returning an empty string, which is causing the problem.

To fix this, you can update your jq expression like this:

```yaml
url: (.response.body.team.name|tostring)
```

Adding `tostring` ensures that missing fields are handled correctly across all requests. Please let me know how it goes!

**Comment by irizzant** [comment]
Thanks @arielsepton I managed to get it working like this:

```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: port-team
spec:
  forProvider:
    waitTimeout: "5m"
    headers:
      Content-Type:
        - application/json
      Authorization:
        - Bearer {{port-token:crossplane-system:token}}
    payload:
      baseUrl: https://api.getport.io/v1/teams
      body: |
        {
          "name": "cost-center-test",
          "users": ["redacted"],
          "description": "Cost Center test team"
        }
    mappings:
      - action: CREATE
        method: POST
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: .payload.baseUrl
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: OBSERVE
        method: GET
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: UPDATE
        method: PUT
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: REMOVE
        method: DELETE
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
```

But I'm facing the same problem now with PUT requests, which are repeated every minute:
```
Events:
  Type    Reason                   Age               From                                Message
  ----    ------                   ----              ----                                -------
  Normal  CreatedExternalResource  63s               managed/request.http.crossplane.io  Successfully requested creation of external resource
  Normal  UpdatedExternalResource  1s (x3 over 63s)  managed/request.http.crossplane.io  Successfully requested update of external resource
```

I had a look [here](https://github.com/crossplane-contrib/provider-http/blob/5efab008b45e01421ef335fd277aed942a93a48d/examples/sample/request.yaml#L68-L77), and I tried to configure the jq expression like this:
```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: port-team
spec:
  forProvider:
    waitTimeout: "5m"
    headers:
      Content-Type:
        - application/json
      Authorization:
        - Bearer {{port-token:crossplane-system:token}}
    payload:
      baseUrl: https://api.getport.io/v1/teams
      body: |
        {
          "name": "cost-center-test",
          "users": ["redacted"],
          "description": "Cost Center test team"
        }
    expectedResponseCheck: # <----- see here
      type: CUSTOM
      logic: |
        if .response.body.team.name == .payload.body.name
         and .response.body.team.users == .payload.body.users
         and .response.body.team.description == .payload.body.description
         then true 
         else false 
         end
    mappings:
      - action: CREATE
        method: POST
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: .payload.baseUrl
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: OBSERVE
        method: GET
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: UPDATE
        method: PUT
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: REMOVE
        method: DELETE
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}

```
But without success. PUT requests are repeated.

Also if I may give you a suggestion, it would be much more helpful having the `status `field reporting not just the response of the last request.

**Comment by arielsepton** [comment]
The `PUT` request is being retried because your `expectedResponseCheck` expression is returning `false`—the `team.users` field doesn’t exist in the GET response.

To fix this, you can update the jq expression like this:

```yaml
expectedResponseCheck: 
  type: CUSTOM
  logic: |
    if .response.body.team.name == .payload.body.name
    and .response.body.team.description == .payload.body.description
    then true 
    else false 
    end
```

As for your suggestion about adding `status`, could you explain a bit more about how you think it would help? Since the status only holds the latest response, I’m curious about what extra benefit you're thinking it might provide.

**Comment by irizzant** [comment]
Thanks @arielsepton for the updates.

But what happens if I change a user in the `users ` field? The logic [you suggested ](https://github.com/crossplane-contrib/provider-http/issues/60#issuecomment-2396683495) would consider the resource updated because it doesnt't use that field right?

In that case I think that's a flaw in the API.

About the `status` field, as you said it reports the status of the latest response. I was thinking that it would be good to know the status of the previous requests as well, because if I have an error I can't see any details about it by inspecting the resource itself.

**Comment by arielsepton** [comment]
I spoke with a tech lead at Port @danielsinai, and it turns out if you add the query parameters `?fields=name&fields=description&fields=users.email`, you can retrieve the users in this format:

```json
"team": { "users": [{"email": "<email>"}, {"email": "<email>"}] }
```

You can update your resource like this:

```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: port-team
spec:
  forProvider:
    waitTimeout: "5m"
    headers:
      Content-Type:
        - application/json
      Authorization:
        - Bearer {{port-token:crossplane-system:token}}
    payload:
      baseUrl: https://api.getport.io/v1/teams
      body: |
        {
          "name": "test",
          "users": ["<email>"],
          "description": "Cost Center test team"
        }
    expectedResponseCheck: 
      type: CUSTOM
      logic: |
        if .response.body.team.name == .payload.body.name
         and (.response.body.team.users | map(.email) | sort) == (.payload.body.users | sort)
         and .response.body.team.description == .payload.body.description
         then true 
         else false 
         end
    mappings:
      - action: CREATE
        method: POST
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: .payload.baseUrl
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: OBSERVE
        method: GET
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring) + "?fields=name&fields=description&fields=users.email")
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: UPDATE
        method: PUT
        body: |
          {
            "name": .payload.body.name,
            "users": .payload.body.users,
            "description": .payload.body.description
          }
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
      - action: REMOVE
        method: DELETE
        url: (.payload.baseUrl + "/" + (.response.body.team.name|tostring))
        headers:
          Content-Type:
            - application/json
          Authorization:
            - Bearer {{port-token:crossplane-system:token}}
```

This should solve the issue.

Regarding the `status` field, while tracking previous request statuses could be helpful for debugging, it might make the field too large and hard to manage.  I think adding more detailed logs could give you the info you need without cluttering the resource, making it easier to trace past requests while keeping `status` focused on the current state.
