### ISSUE TITLE
Request spec doesn't get updated with new action feature

### ISSUE THREAD

**Issue by miguellobato84** [crossplane-contrib/provider-http#64]
Hello!

I've testing latest action feature and works great. I didn't manage to get the exact reason, but when deleting the resource it raises the following error:
```Mapping not found for action OBSERVE, trying to find mapping by method GET        {"request": "create-key"}```

Taking a look at the spec, actions are not there. Example:
```yaml
spec:
  deletionPolicy: Delete
  forProvider:
    headers:
      Authorization:
        - ("Bearer xxxxx")
      Content-Type:
        - application/json
    insecureSkipTLSVerify: true
    mappings:
      - body: |
          {
            "team_id": .payload.body.team_id, 
            "team_alias": .payload.body.team_alias, 
            "max_budget": .payload.body.max_budget,
            "tpm_limit": .payload.body.tpm_limit,
            "rpm_limit": .payload.body.rpm_limit,
            "blocked": .payload.body.blocked
          }
        method: POST
        url: (.payload.baseUrl + "/team/new")
      - method: GET
        url: >-
          (.payload.baseUrl + "/team/info?team_id=" +
          (.payload.body.team_id|tostring))
      - body: |
          {
            "team_id": .payload.body.team_id, 
            "team_alias": .payload.body.team_alias, 
            "max_budget": .payload.body.max_budget,
            "tpm_limit": .payload.body.tpm_limit,
            "rpm_limit": .payload.body.rpm_limit,
            "blocked": .payload.body.blocked
          }
        method: POST
        url: (.payload.baseUrl + "/team/update")
      - body: |
          {
            "team_ids": [.payload.body.team_id]
          }
        method: POST
        url: (.payload.baseUrl + "/team/delete")
    payload:
      baseUrl: xxxxxx
      body: |
        {
            "team_id": "test",
            "team_alias": "test",
            "max_budget": 100,
            "tpm_limit": 50,
            "rpm_limit": 50,
            "blocked": false
        }
    waitTimeout: 5m0s
```

for reference, this is the request manifest
```yaml
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: create-key
spec:
  forProvider:
    insecureSkipTLSVerify: true
    waitTimeout: 5m
    headers:
      Content-Type:
        - application/json
      Authorization:
        - ("Bearer xxxx")
    payload:
      baseUrl: xxxx
      body: |
        {
            "key_alias": "test",
            "team_id": "test"
        }
    mappings:
      - action: CREATE
        method: "POST"
        url: (.payload.baseUrl + "/key/generate")
        body: |
          {
            "key_alias": .payload.body.key_alias,
            "team_id": .payload.body.team_id
          }
      - action: OBSERVE
        method: "GET"
        url: (.payload.baseUrl + "/key/info?key=" + (.response.body.key|tostring))
      - action: UPDATE
        method: "POST"
        url: (.payload.baseUrl + "/key/update")
        body: |
          {
            "key": .response.body.key, 
            "key_alias": .payload.body.key_alias, 
            "team_id": .payload.body.team_id
          }
      - action: REMOVE
        method: "POST"
        url: (.payload.baseUrl + "/key/delete")
        body: |
          {
            "keys": [.response.body.key]
          }
    expectedResponseCheck:
      type: CUSTOM
      logic: |
        if .response.body.info.key_alias == .payload.body.key_alias
         and .response.body.info.team_id == .payload.body.team_id
         then true
         else false
         end

  providerConfigRef:
    name: http-conf

```

Thanks!
