### ISSUE TITLE
How to use XRC/claim values in DisposableRequest body

### ISSUE THREAD

**Issue by bjartekh** [crossplane-contrib/provider-http#66]
### What problem are you facing?

I'm uncertain how I can get values supplied in my XRC(claim) substituted in the body of a DisposableRequest.

Here's an example of my 3 files.

The XRD:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: mycomposition.test.me.net
spec:
  group: test.me.net
  names:
    kind: mycomposition
    plural: mycompositions
  claimNames:
    kind: lz1Claim
    plural: lz1claim    
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              TestFlag: 
                type: boolean
                default: true
              TestValue:
                type: string
```

My XRC (claim)

```yaml
apiVersion: test.me.net/v1alpha1
kind: lz1Claim
metadata:
  name: my-test-project
spec:
  compositionRef:
    name: my-composition
  TestFlag: false
  TestValue: "myvalue"
```

And my composition (using provider-http, DisposableRequest)

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: my-composition
spec:
  resources:
    - name: http-request
      base: 
        apiVersion: http.crossplane.io/v1alpha2
        kind: DisposableRequest
        spec:
          providerConfigRef:
            name: http-test-config
          deletionPolicy: Orphan
          forProvider:
            body: |
              {
                "jsonParams": {
                    "TestFlag": ".spec.TestFlag",
                    "TestValue": "{{ .spec.TestValue }}"
                }
              }
            expectedResponse: .body.state == "inProgress"
            headers:
              Authorization:
                - "Basic {{ my-secret-external:crossplane-system:authorization }}"
              Content-Type:
                - application/json
            insecureSkipTLSVerify: true
            method: POST
            rollbackRetriesLimit: 1
            url: https://mytestdomain.com/testme/pipeline/execute
            waitTimeout: 5m

```

I see that the request is sent, but no substitution happens of the values supplied in the body.
I've tried various syntax too.

### How could Crossplane help solve your problem?

Maybe you could add some examples of how this is done? (I looked at the examples provided and couldn't find any, it seems that the examples uses values hardcoded in the body).

It is not clear to me how I could use crossplane patches because the `body` type is a string.

**Comment by arielsepton** [comment]
Yes, the body is a string because CRDs don’t support an `interface{}` type, so all fields must be predefined. 
To dynamically substitute values in the string body, you can use Crossplane’s [function-go-templating](http://github.com/crossplane-contrib/function-go-templating)—I recommend giving it a try!

Alternatively, you could use patches and transforms, as described in [Crossplane’s patch and transform guide](https://github.com/crossplane/docs/blob/master/content/v1.17/guides/function-patch-and-transform.md#L1240). For example:

```yaml
- type: FromCompositeFieldPath
  fromFieldPath: spec.clusterName
  toFieldPath: spec.forProvider.tags
  transforms:
    - type: string
      string:
        type: Format
        fmt: '{"kubernetes.io/cluster/%s": "true"}'
```

Since this issue is about general Crossplane composition patterns rather than the specific provider, I’ll go ahead and close it. Let me know if this helps or if you have further questions!

**Comment by bjartekh** [comment]
Hi again, I've checked out your examples but not been able to substitute the string body. I'll also add that I'm not super-experienced with Crossplane. 

It would be very valuable if you could provide an example.

(I am also assuming that this would be of value for other than me, as one often wants to dynamically provide the values of a post body)

**Comment by arielsepton** [comment]
Hi there,
Here’s a starting example that might work:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: my-composition
spec:
  resources:
    - name: http-request
      base: 
        apiVersion: http.crossplane.io/v1alpha2
        kind: DisposableRequest
        spec:
          providerConfigRef:
            name: http-test-config
          deletionPolicy: Orphan
          forProvider:
            headers:
              Authorization:
                - "Basic {{ my-secret-external:crossplane-system:authorization }}"
              Content-Type:
                - application/json
            insecureSkipTLSVerify: true
            method: POST
            url: https://mytestdomain.com/testme/pipeline/execute
    patches:
      - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.TestFlag
            - fromFieldPath: spec.TestValue
          strategy: string
          string:
            fmt: |
              {
                "jsonParams": {
                  "TestFlag": "%s",
                  "TestValue": "%s"
                }
              }
        toFieldPath: spec.forProvider.body
```

This is untested, but it should give you an idea of how to use `patches` to patch values into the `body`.

For more guidance, I recommend looking at the [CombineFromComposite documentation](https://docs.crossplane.io/v1.15/concepts/patch-and-transform/) and reaching out to the  [Crossplane Slack community](https://slack.crossplane.io/)—they’re very helpful, and this type of composition question is right in line with what they handle best. Let me know if this points you in the right direction!
