### ISSUE TITLE
Prevent secretInjectionConfigs from setting empty value for key that is not present

### ISSUE THREAD

**Issue by schaschko** [crossplane-contrib/provider-http#81]
Is there a way to use `secretInjectionConfigs` in combination with `Request`, but don't have the Secret updated after `CREATE`.

E.g. [this API](https://docs.stripe.com/api/webhook_endpoints/object#webhook_endpoint_object-secret) will return a field `secret` only on `CREATE`. Afterwards (`OBSERVE`) this field is just not in the response at all. Is there any way, to have a resource like this managed by `Request` (not `DisposableRequest`) while keeping the response value that was returned on the first `CREATE` request?

Or stated differently: if there is a field (e.g. `secret` like in this example) that's seen in the (first) response, but not on subsequent requests, should it be updated at all when it's not even there anymore? At the moment it is, meaning the corresponding key's value in the K8s `Secret` is emptied.

**Comment by klaudworks** [comment]
I see two different solutions to deal with APIs that do not return every field on every request e.g Stripe:

Solution 1: If a field is not returned from a request just leave the secret as it is. This is not really backwards compatible though and in most cases it is probably intended behavior to assume if something is not returned it is set to "null".

Solution 2: We could add a extra field for the SecretInjectionConfigs to deal with such APIs. That would be backwards compatible.

Possible solutions could be:

1. add a sync policy that specifies if updates/deletes should be performed.

```yaml
---
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: stripe-example
spec:
    ...
    secretInjectionConfigs:
        secretRef:
          name: example-secret
          namespace: example
        keyMappings:
          - secretKey: secret
            responseJQ: ".body.secret"
            syncPolicy:
              update: true
              delete: false
```

2. add a field `preserveExisting` to prevent deletion of existing fields if the counterpart is not explicitly returned by the API.

```yaml
---
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: stripe-example
spec:
    ...
    secretInjectionConfigs:
        secretRef:
          name: example-secret
          namespace: example
        keyMappings:
          - secretKey: secret
            responseJQ: ".body.secret"
            preserveExisting: true
```



I'd be open to implement this behavior if one of the maintainers approves the API change.

**Comment by arielsepton** [comment]
Thanks for the suggestions! I really like the idea behind the first solution, but I think the `syncPolicy` naming could be improved. What do you think about this approach?

```
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: stripe-example
spec:
  ...
  secretInjectionConfigs:
    secretRef:
      name: example-secret
      namespace: example
    keyMappings:
      - secretKey: secret
        responseJQ: ".body.secret"
        preserveOnMissing: true  # Preserves the existing value if the field is missing in the response
        preserveOnDelete: true   # Prevents deletion if the field is no longer returned

```

I’d be happy to approve this if you’re interested in implementing it!
