### ISSUE TITLE
Using a Request to manage Jira ticket lifecycle

### ISSUE THREAD

**Issue by zahaim** [crossplane-contrib/provider-http#82]
Hi there,

I use crossplane for self-service to our development teams to manage simple firewall openings. We are requested to document such changes with a Jira ticket. So far I managed to create a ticket on firewall change claim creation and add a comment to the ticket when the firewall change claim is deleted.
What I would like to achieve is to manage Jira ticket status too: make it "In progress" when the claim is created (but not ready), then "Done" when it's ready and "Cancelled" when the claim is removed. 
When I enable a part of my code which is commented out, crossplane creates new Jira ticket every minute. I guess this is related to the fact that it's a POST (I cannot use PUT as this is how Jira API works). Also, I don't know how to make other Jira status transitions.

As managing Jira ticket seems to be a common use case (well, at least I think so), maybe someone already have a working solution to share. Otherwise, any ideas would be appreciated, thanks.

So far my code looks as follows:

```
apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  annotations:
    {{ setResourceNameAnnotation "httpPost" }}
    crossplane.io/external-name: "httpPost"
spec:
  forProvider:
    waitTimeout: 5m
    headers:
      Content-Type: 
        - "application/json"
      Accept: 
        - "application/json"
      Authorization:
        - "Basic {{ .observed.resources.jiraApiSecret.resource.status.atProvider.manifest.data.password }}"
    payload:
      baseUrl: https://company.atlassian.net/rest/api/2/issue/
      body: |
        {"fields":
            {"project":
              {"id":"66666"},
            "issuetype":
              {"id":"66"},
            "summary":"Automated Firewall change {{ $spec.environment }}",
            "description": "*Business justification:*\n{color:green}{{ $spec.business_case }}{color}"
            }
        }                    
    mappings:
      - action: CREATE
        # method: "POST" # defaults POST for CREATE
        body: .payload.body
        url: .payload.baseUrl
      - action: OBSERVE
        # method: "GET" # defaults to GET for OBSERVE
        url: (.payload.baseUrl + (.response.body.key|tostring))
      # - method: "POST" # Jira transition only works with POST
      #   action: UPDATE # change ticket status to "In Progress"
      #   url: (.payload.baseUrl + (.response.body.key|tostring) + "/transitions")
      #   body: |
      #     {
      #         "transition": {
      #             "id": "221"
      #         }
      #     }
      - action: REMOVE
        method: "POST"
        url: (.payload.baseUrl + (.response.body.key|tostring) + "/comment")
        body: |
          {
            body: "Automated message: *Firewall rule deleted.*\nTicket left for reference."
          }                    
    isRemovedCheck:
      type: CUSTOM
      logic: |
        if .response.body.fields.comment.total != 0 // false
          then true
          else false 
          end                      
  providerConfigRef:
    name: provider-http
```

**Comment by arielsepton** [comment]
Hey!

I think you can use the [expectedResponseCheck](https://github.com/crossplane-contrib/provider-http/blob/main/examples/sample/request.yaml#L69) field to avoid repeated `POST` requests when managing Jira ticket status. 
It allows you to validate the response and ensure the desired state before sending another `CREATE` request.

Here's an example:
```yaml

apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  annotations:
    {{ setResourceNameAnnotation "httpPost" }}
    crossplane.io/external-name: "httpPost"
spec:
  forProvider:
    waitTimeout: 5m
    headers:
      Content-Type: 
        - "application/json"
      Accept: 
        - "application/json"
      Authorization:
        - "Basic {{ .observed.resources.jiraApiSecret.resource.status.atProvider.manifest.data.password }}"
    payload:
      baseUrl: https://company.atlassian.net/rest/api/2/issue/
      body: |
        {
          "fields": {
            "project": {
              "id": "66666"
            },
            "issuetype": {
              "id": "66"
            },
            "summary": "Automated Firewall change {{ $spec.environment }}",
            "description": "*Business justification:*\n{color:green}{{ $spec.business_case }}{color}",
            "status": "In Progress"
          }
        }                    
    mappings:
      - action: CREATE
        # method: "POST" # defaults to POST for CREATE
        body: .payload.body
        url: .payload.baseUrl

      - action: OBSERVE
        # method: "GET" # defaults to GET for OBSERVE
        url: (.payload.baseUrl + (.response.body.key|tostring))

      - action: UPDATE # change ticket status based on payload
        method: "POST"
        url: (.payload.baseUrl + (.response.body.key|tostring) + "/transitions")
        body: |
          {
            "transition": {
              "id": {{ if eq .payload.body.fields.status "In Progress" }} "221" {{ else if eq .payload.body.fields.status "Done" }} "222" {{ else if eq .payload.body.fields.status "Cancelled" }} "223" {{ end }}
            }
          }

      - action: REMOVE
        method: "POST"
        url: (.payload.baseUrl + (.response.body.key|tostring) + "/comment")
        body: |
          {
            "body": "Automated message: *Firewall rule deleted.*\nTicket left for reference."
          }                    
    isRemovedCheck:
      type: CUSTOM
      logic: |
        if .response.body.fields.comment.total != 0 
        then true
        else false 
        end

    expectedResponseCheck:
      type: CUSTOM
      logic: |
        if .response.body.fields.status.name == .payload.body.fields.status
        then true
        else false
        end                      
  providerConfigRef:
    name: provider-http

```

This will ensure the creation and updates only happens if the ticket isn’t already in the desired status which is written in the `payload`, preventing repeated POSTs.

Note: I’m not very familiar with the Jira API, but this approach should give you a sense of how you can structure it. Let me know if this helps or if you need further clarification!
